# coding: utf-8

"""
    Unit API V3

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class UnitMapItem(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'from_namespace': 'str',
        'from_unit': 'Unit',
        'note': 'str',
        'state': 'str',
        'to_namespace': 'str',
        'to_unit': 'Unit'
    }

    attribute_map = {
        'from_namespace': 'fromNamespace',
        'from_unit': 'fromUnit',
        'note': 'note',
        'state': 'state',
        'to_namespace': 'toNamespace',
        'to_unit': 'toUnit'
    }

    def __init__(self, from_namespace=None, from_unit=None, note=None, state=None, to_namespace=None, to_unit=None):
        """
        UnitMapItem - a model defined in Swagger
        """

        self._from_namespace = None
        self._from_unit = None
        self._note = None
        self._state = None
        self._to_namespace = None
        self._to_unit = None

        if from_namespace is not None:
          self.from_namespace = from_namespace
        if from_unit is not None:
          self.from_unit = from_unit
        if note is not None:
          self.note = note
        if state is not None:
          self.state = state
        if to_namespace is not None:
          self.to_namespace = to_namespace
        if to_unit is not None:
          self.to_unit = to_unit

    @property
    def from_namespace(self):
        """
        Gets the from_namespace of this UnitMapItem.

        :return: The from_namespace of this UnitMapItem.
        :rtype: str
        """
        return self._from_namespace

    @from_namespace.setter
    def from_namespace(self, from_namespace):
        """
        Sets the from_namespace of this UnitMapItem.

        :param from_namespace: The from_namespace of this UnitMapItem.
        :type: str
        """

        self._from_namespace = from_namespace

    @property
    def from_unit(self):
        """
        Gets the from_unit of this UnitMapItem.

        :return: The from_unit of this UnitMapItem.
        :rtype: Unit
        """
        return self._from_unit

    @from_unit.setter
    def from_unit(self, from_unit):
        """
        Sets the from_unit of this UnitMapItem.

        :param from_unit: The from_unit of this UnitMapItem.
        :type: Unit
        """

        self._from_unit = from_unit

    @property
    def note(self):
        """
        Gets the note of this UnitMapItem.

        :return: The note of this UnitMapItem.
        :rtype: str
        """
        return self._note

    @note.setter
    def note(self, note):
        """
        Sets the note of this UnitMapItem.

        :param note: The note of this UnitMapItem.
        :type: str
        """

        self._note = note

    @property
    def state(self):
        """
        Gets the state of this UnitMapItem.

        :return: The state of this UnitMapItem.
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """
        Sets the state of this UnitMapItem.

        :param state: The state of this UnitMapItem.
        :type: str
        """

        self._state = state

    @property
    def to_namespace(self):
        """
        Gets the to_namespace of this UnitMapItem.

        :return: The to_namespace of this UnitMapItem.
        :rtype: str
        """
        return self._to_namespace

    @to_namespace.setter
    def to_namespace(self, to_namespace):
        """
        Sets the to_namespace of this UnitMapItem.

        :param to_namespace: The to_namespace of this UnitMapItem.
        :type: str
        """

        self._to_namespace = to_namespace

    @property
    def to_unit(self):
        """
        Gets the to_unit of this UnitMapItem.

        :return: The to_unit of this UnitMapItem.
        :rtype: Unit
        """
        return self._to_unit

    @to_unit.setter
    def to_unit(self, to_unit):
        """
        Sets the to_unit of this UnitMapItem.

        :param to_unit: The to_unit of this UnitMapItem.
        :type: Unit
        """

        self._to_unit = to_unit

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, UnitMapItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
