# coding: utf-8

"""
    Unit Service API

    Unit and Measurement Service

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.units_api import UnitsApi


class TestUnitsApi(unittest.TestCase):
    """ UnitsApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.units_api.UnitsApi()

    def tearDown(self):
        pass

    def test_get_preferred_units_by_measurement(self):
        """
        Test case for get_preferred_units_by_measurement

        Get preferred Units for a Measurement
        """
        pass

    def test_get_preferred_units_by_measurement_ancestry(self):
        """
        Test case for get_preferred_units_by_measurement_ancestry

        Get preferred Units for a Measurement by ancestry
        """
        pass

    def test_get_unit(self):
        """
        Test case for get_unit

        Get a specific Unit
        """
        pass

    def test_get_unit_by_namespace_and_symbol(self):
        """
        Test case for get_unit_by_namespace_and_symbol

        Get a unique Unit by Namespace,Symbol
        """
        pass

    def test_get_unit_map_items(self):
        """
        Test case for get_unit_map_items

        Get Unit maps between namespaces
        """
        pass

    def test_get_units(self):
        """
        Test case for get_units

        Get all Units
        """
        pass

    def test_get_units_by_measurement_ancestry(self):
        """
        Test case for get_units_by_measurement_ancestry

        Get all Units for a Measurement by ancestry
        """
        pass

    def test_get_units_by_symbol(self):
        """
        Test case for get_units_by_symbol

        Get Units by symbol
        """
        pass

    def test_get_units_for_measurement(self):
        """
        Test case for get_units_for_measurement

        Get all Units for a Measurement
        """
        pass

    def test_search_units(self):
        """
        Test case for search_units

        Search Units by keyword(s)
        """
        pass


if __name__ == '__main__':
    unittest.main()
