# coding: utf-8

"""
    Unit Service API

    Unit and Measurement Service

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.uo_m_catalog_api import UoMCatalogApi


class TestUoMCatalogApi(unittest.TestCase):
    """ UoMCatalogApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.uo_m_catalog_api.UoMCatalogApi()

    def tearDown(self):
        pass

    def test_get_catalog_summary(self):
        """
        Test case for get_catalog_summary

        Get the entire Catalog
        """
        pass

    def test_get_last_modified_date(self):
        """
        Test case for get_last_modified_date

        Gets the Catalog's last modified date
        """
        pass

    def test_get_map_states(self):
        """
        Test case for get_map_states

        Get the map and/or deprecation states
        """
        pass

    def test_search_entire_catalog(self):
        """
        Test case for search_entire_catalog

        Search Catalog by keyword(s)
        """
        pass


if __name__ == '__main__':
    unittest.main()
