# coding: utf-8

"""
    Unit Service API

    Unit and Measurement Service

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.info_api_api_slash import InfoApiApiSlash


class TestInfoApiApiSlash(unittest.TestCase):
    """ InfoApiApiSlash unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.info_api_api_slash.InfoApiApiSlash()

    def tearDown(self):
        pass

    def test_info_using_get(self):
        """
        Test case for info_using_get

        info
        """
        pass


if __name__ == '__main__':
    unittest.main()
