# coding: utf-8

"""
    Unit Service API

    Unit and Measurement Service

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.measurements_api import MeasurementsApi


class TestMeasurementsApi(unittest.TestCase):
    """ MeasurementsApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.measurements_api.MeasurementsApi()

    def tearDown(self):
        pass

    def test_get_measurement(self):
        """
        Test case for get_measurement

        Get a specific Measurement
        """
        pass

    def test_get_measurement_by_ancestry(self):
        """
        Test case for get_measurement_by_ancestry

        Get a specific Measurement by ancestry
        """
        pass

    def test_get_measurement_map_items(self):
        """
        Test case for get_measurement_map_items

        Get the Measurement maps between namespaces
        """
        pass

    def test_get_measurements(self):
        """
        Test case for get_measurements

        Get all Measurements
        """
        pass

    def test_search_measurements(self):
        """
        Test case for search_measurements

        Search Measurements by keyword(s)
        """
        pass


if __name__ == '__main__':
    unittest.main()
