# coding: utf-8

"""
    Unit Service API

    Unit and Measurement Service

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.conversion_abcd_request import ConversionAbcdRequest


class TestConversionAbcdRequest(unittest.TestCase):
    """ ConversionAbcdRequest unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConversionAbcdRequest(self):
        """
        Test ConversionAbcdRequest
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.conversion_abcd_request.ConversionAbcdRequest()
        pass


if __name__ == '__main__':
    unittest.main()
