# coding: utf-8

"""
    Unit Service API

    Unit and Measurement Service

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.unit_systems_api import UnitSystemsApi


class TestUnitSystemsApi(unittest.TestCase):
    """ UnitSystemsApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.unit_systems_api.UnitSystemsApi()

    def tearDown(self):
        pass

    def test_get_unit_by_unit_system_and_measurement(self):
        """
        Test case for get_unit_by_unit_system_and_measurement

        Get a unique Unit for the given Measurement in the named UnitSystem
        """
        pass

    def test_get_unit_by_unit_system_and_measurement_ancestry(self):
        """
        Test case for get_unit_by_unit_system_and_measurement_ancestry

        Get a unique Unit for the given Measurement ancestry in the named UnitSystem
        """
        pass

    def test_get_unit_system_by_essence(self):
        """
        Test case for get_unit_system_by_essence

        Get all Units assigned to the UnitSystem
        """
        pass

    def test_get_unit_system_by_name(self):
        """
        Test case for get_unit_system_by_name

        Get all Units assigned to the UnitSystem name
        """
        pass

    def test_get_unit_system_list(self):
        """
        Test case for get_unit_system_list

        Get all UnitSystem info
        """
        pass


if __name__ == '__main__':
    unittest.main()
