# coding: utf-8

"""
    Unit Service API

    Unit and Measurement Service

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.measurement_map import MeasurementMap


class TestMeasurementMap(unittest.TestCase):
    """ MeasurementMap unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMeasurementMap(self):
        """
        Test MeasurementMap
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.measurement_map.MeasurementMap()
        pass


if __name__ == '__main__':
    unittest.main()
