# coding: utf-8

"""
    Unit Service API

    Unit and Measurement Service

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.conversions_api import ConversionsApi


class TestConversionsApi(unittest.TestCase):
    """ ConversionsApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.conversions_api.ConversionsApi()

    def tearDown(self):
        pass

    def test_get_conversion_as_abcd(self):
        """
        Test case for get_conversion_as_abcd

        Get Abcd Unit conversion parameters given two Units
        """
        pass

    def test_get_conversion_as_abcd_by_namespace_and_symbols(self):
        """
        Test case for get_conversion_as_abcd_by_namespace_and_symbols

        Get Abcd Unit conversion parameters given two Unit specifications
        """
        pass

    def test_get_conversion_as_scale_offset(self):
        """
        Test case for get_conversion_as_scale_offset

        Get ScaleOffset Unit conversion parameters given two Units
        """
        pass

    def test_get_conversion_as_scale_offset_by_namespace_and_symbols(self):
        """
        Test case for get_conversion_as_scale_offset_by_namespace_and_symbols

        Get ScaleOffset Unit conversion parameters given two unit specifications
        """
        pass


if __name__ == '__main__':
    unittest.main()
