# coding: utf-8

"""
    Unit Service API

    Unit and Measurement Service

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.unit_system_essence import UnitSystemEssence


class TestUnitSystemEssence(unittest.TestCase):
    """ UnitSystemEssence unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUnitSystemEssence(self):
        """
        Test UnitSystemEssence
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.unit_system_essence.UnitSystemEssence()
        pass


if __name__ == '__main__':
    unittest.main()
