# coding: utf-8

"""
    Unit API V3

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.unitapiv3_api import Unitapiv3Api


class TestUnitapiv3Api(unittest.TestCase):
    """ Unitapiv3Api unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.unitapiv3_api.Unitapiv3Api()

    def tearDown(self):
        pass

    def test_get_catalog_using_get(self):
        """
        Test case for get_catalog_using_get

        getCatalog
        """
        pass

    def test_get_conversion_abcd_by_symbols_using_get(self):
        """
        Test case for get_conversion_abcd_by_symbols_using_get

        getConversionABCDBySymbols
        """
        pass

    def test_get_conversion_scale_offset_by_symbols_using_get(self):
        """
        Test case for get_conversion_scale_offset_by_symbols_using_get

        getConversionScaleOffsetBySymbols
        """
        pass

    def test_get_last_modified_using_get(self):
        """
        Test case for get_last_modified_using_get

        getLastModified
        """
        pass

    def test_get_map_states_using_get(self):
        """
        Test case for get_map_states_using_get

        getMapStates
        """
        pass

    def test_get_measurement_maps_using_get(self):
        """
        Test case for get_measurement_maps_using_get

        getMeasurementMaps
        """
        pass

    def test_get_measurement_using_get(self):
        """
        Test case for get_measurement_using_get

        getMeasurement
        """
        pass

    def test_get_measurements_using_get(self):
        """
        Test case for get_measurements_using_get

        getMeasurements
        """
        pass

    def test_get_preferred_units_by_measurement_using_get(self):
        """
        Test case for get_preferred_units_by_measurement_using_get

        getPreferredUnitsByMeasurement
        """
        pass

    def test_get_unit_by_symbol_using_get(self):
        """
        Test case for get_unit_by_symbol_using_get

        getUnitBySymbol
        """
        pass

    def test_get_unit_by_system_and_measurement_using_get(self):
        """
        Test case for get_unit_by_system_and_measurement_using_get

        getUnitBySystemAndMeasurement
        """
        pass

    def test_get_unit_maps_using_get(self):
        """
        Test case for get_unit_maps_using_get

        getUnitMaps
        """
        pass

    def test_get_unit_system_info_list_using_get(self):
        """
        Test case for get_unit_system_info_list_using_get

        getUnitSystemInfoList
        """
        pass

    def test_get_unit_system_using_get(self):
        """
        Test case for get_unit_system_using_get

        getUnitSystem
        """
        pass

    def test_get_units_by_measurement_using_get(self):
        """
        Test case for get_units_by_measurement_using_get

        getUnitsByMeasurement
        """
        pass

    def test_get_units_by_symbol_using_get(self):
        """
        Test case for get_units_by_symbol_using_get

        getUnitsBySymbol
        """
        pass

    def test_get_units_using_get(self):
        """
        Test case for get_units_using_get

        getUnits
        """
        pass

    def test_post_conversion_abcd_using_post(self):
        """
        Test case for post_conversion_abcd_using_post

        postConversionABCD
        """
        pass

    def test_post_conversion_scale_offset_using_post(self):
        """
        Test case for post_conversion_scale_offset_using_post

        postConversionScaleOffset
        """
        pass

    def test_post_measurement_using_post(self):
        """
        Test case for post_measurement_using_post

        postMeasurement
        """
        pass

    def test_post_preferred_units_by_measurement_using_post(self):
        """
        Test case for post_preferred_units_by_measurement_using_post

        postPreferredUnitsByMeasurement
        """
        pass

    def test_post_search_measurements_using_post(self):
        """
        Test case for post_search_measurements_using_post

        postSearchMeasurements
        """
        pass

    def test_post_search_units_using_post(self):
        """
        Test case for post_search_units_using_post

        postSearchUnits
        """
        pass

    def test_post_search_using_post(self):
        """
        Test case for post_search_using_post

        postSearch
        """
        pass

    def test_post_unit_by_system_and_measurement_using_post(self):
        """
        Test case for post_unit_by_system_and_measurement_using_post

        postUnitBySystemAndMeasurement
        """
        pass

    def test_post_unit_system_using_post(self):
        """
        Test case for post_unit_system_using_post

        postUnitSystem
        """
        pass

    def test_post_unit_using_post(self):
        """
        Test case for post_unit_using_post

        postUnit
        """
        pass

    def test_post_units_by_measurement_using_post(self):
        """
        Test case for post_units_by_measurement_using_post

        postUnitsByMeasurement
        """
        pass


if __name__ == '__main__':
    unittest.main()
