# coding: utf-8

"""
    Unit API V3

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.infoapi_api import InfoapiApi


class TestInfoapiApi(unittest.TestCase):
    """ InfoapiApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.infoapi_api.InfoapiApi()

    def tearDown(self):
        pass

    def test_info_using_get(self):
        """
        Test case for info_using_get

        info
        """
        pass


if __name__ == '__main__':
    unittest.main()
