# coding: utf-8

"""
    Unit API V3

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.unit_system_essence_impl import UnitSystemEssenceImpl


class TestUnitSystemEssenceImpl(unittest.TestCase):
    """ UnitSystemEssenceImpl unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUnitSystemEssenceImpl(self):
        """
        Test UnitSystemEssenceImpl
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.unit_system_essence_impl.UnitSystemEssenceImpl()
        pass


if __name__ == '__main__':
    unittest.main()
