apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ printf "%s-jwt-authz" .Values.conf.appName | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.conf.appName | quote }}
  action: ALLOW
  rules:
    - from:
        - source:
            requestPrincipals: ["*"]

    - to:
        - operation:
            paths:
              {{- $base := .Values.istio.auth.basePath }}

              #global paths (starting with /) → no duplication
              {{- range $p := .Values.istio.auth.disable }}
              {{- if hasPrefix "/" $p }}
              - {{ $p | quote }}
              {{- end }}
              {{- end }}

              #versioned paths (no leading /)
              {{- range $version := .Values.istio.auth.versions }}
              {{- range $p := $.Values.istio.auth.disable }}
              {{- if not (hasPrefix "/" $p) }}
              - "{{ $base }}/{{ $version }}/{{ $p }}"
              {{- end }}
              {{- end }}
              {{- end }}
