apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ printf "%s-jwt-authz" .Values.conf.appName | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.conf.appName | quote }}
  action: DENY
  rules:
    - from:
        - source:
            notRequestPrincipals: ["*"]
      to:
        - operation:
            notPaths:
              {{- range .Values.istio.auth.disable }}
              - {{ . | quote }}
              {{- end }}
